pipeline{
    agent any
    environment{
        VERSION = "V1"
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages{
        stage('Build images'){
            steps{
                echo "build flask app - use version "
                sh "docker build -t ${DOCKERHUB_CREDS_USR}/task1-flask-app:${VERSION} Task1"
                echo "build nginx - use version "
            }     
        }
        stage('Deploy containers'){
            steps{
                echo "delete any old images"
                sh "docker build -t ${DOCKERHUB_CREDS_USR}/task1-flask-app:${VERSION} Task1"
                echo "create network"   
                echo "remove any containers" 
                echo "deploy flak app on network with pass for YOUR_NAME (docker run image:version)" 
                echo "DEPLOY nginx with port "    
            }     
        }
        stage('Push to   docker hub'){
            steps{
                echo "login to dockerhub with credentials"   
                echo "push flask app" 
                echo "push nginx" 
                echo "logout of dockerhub "    
            }     
        }
        stage('tidy up'){
            steps{
                echo "delete old containers"
                //delete old images (not current version as is image for running container)
            }
        }
    }
}